# docker-compose.yml

version: '3.8'

services:
  monitor-listas:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: painel-monitor-listas
    restart: always
    ports:
      - "8080:80"
    environment:
      # Injeção de rotas de configuração prioritárias para o Runtime Linux
      - ADVICE_XML_PATH=/app/config_advice/Advice.xml
      - MonitorSettings__CaminhoPasta=/app/xml_origem
      - TZ=America/Sao_Paulo
    volumes:
      # Espelhamento da pasta de origem de XMLs (Drop do ERP via Syncthing)
      - /mnt/syncthing_dados/ListasRestritiva/in:/app/xml_origem
      
      # Mapeamento do diretório de configurações externas (Advice.xml e TRIBUNAIS.CRIPTO)
      - /opt/advice_configs:/app/config_advice
      
      # Persistência do banco de dados SQLite (evita perda de dados no restart do container)
      - monitor_db_data:/app/dados
      
      # Persistência do diretório de isolamento (Quarentena) de XMLs inválidos
      - monitor_quarentena_data:/app/Quarentena_XML

volumes:
volumes:
      # O lado ESQUERDO é o seu Windows. O lado DIREITO é dentro do Docker.
      
      # 1. Onde caem os XMLs hoje na sua rede (ou numa pasta de teste na sua máquina)
      - \\192.168.0.202\publico\Lsantos\ListasRestritiva\in:/app/xml_origem
      
      # 2. Onde está o seu advice.xml e o arquivo de senha (CRIPTO) localmente
      - C:\ADVICE\config:/app/config_advice
      
      # 3 e 4. Mantemos os volumes gerenciados pelo Docker para o banco e quarentena
      - monitor_db_data:/app/dados
      - monitor_quarentena_data:/app/Quarentena_XML