# docker-compose.yml

version: '3.8'

services:
  monitor-listas:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: painel-monitor-listas
    restart: always
    ports:
      - "8080:80"
    environment:
      # Injeção de rotas de configuração prioritárias para o Runtime Linux
      - ADVICE_XML_PATH=/app/config_advice/Advice.xml
      - MonitorSettings__CaminhoPasta=/app/xml_origem
      - TZ=America/Sao_Paulo
    volumes:
      # Espelhamento da pasta de origem de XMLs (Drop do ERP via Syncthing)
      - /mnt/syncthing_dados/ListasRestritiva/in:/app/xml_origem
      
      # Mapeamento do diretório de configurações externas (Advice.xml e TRIBUNAIS.CRIPTO)
      - /opt/advice_configs:/app/config_advice
      
      # Persistência do banco de dados SQLite (evita perda de dados no restart do container)
      - monitor_db_data:/app/dados
      
      # Persistência do diretório de isolamento (Quarentena) de XMLs inválidos
      - monitor_quarentena_data:/app/Quarentena_XML

volumes:
  monitor_db_data:
  monitor_quarentena_data: