version: '3.8'

services:
  monitor-listas:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: painel-monitor-listas
    restart: always
    ports:
      - "8080:80"
    environment:
      - ADVICE_XML_PATH=/app/config_advice/Advice.xml
      - MonitorSettings__CaminhoPasta=/app/xml_origem
      - TZ=America/Sao_Paulo
      
    # 1º VOLUMES (Com 4 espaços de recuo - pertence ao C#)
    volumes:
      - \\192.168.0.202\publico\Lsantos\ListasRestritiva\in:/app/xml_origem
      - C:\ADVICE\config:/app/config_advice
      - monitor_db_data:/app/dados
      - monitor_quarentena_data:/app/Quarentena_XML

# 2º VOLUMES (Colado na margem esquerda - pertence ao Docker Global)
volumes:
  monitor_db_data:
  monitor_quarentena_data: